library(Seurat)
source('dimes.R')
exprs <- read.csv("cell_line/GSE65525/GSM1599500_K562_cells.csv", row.names=1)
leuk <- CreateSeuratObject(counts=exprs, min.cells=3,min.features=200)
leuk <- NormalizeData(object=leuk, normalization.method = "LogNormalize", scale.factor = 1e4)
leuk <- FindVariableFeatures(leuk)
leuk <- ScaleData(object=leuk, features=rownames(leuk))
aucs <- ppi_comp(leuk)
write.csv(aucs, file="aucs/K652.csv")